"""Trend filtering helpers built on top of SuSiE."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from ._utils import ensure_1d


@dataclass(frozen=True)
class TrendFilterResult:
    design: np.ndarray
    signal: np.ndarray
    changepoints: np.ndarray
    order: int
    model: object
    result: object


def trend_filter_design(n: int, order: int = 0) -> np.ndarray:
    """Build a 1D trend-filter design matrix.

    For order=0, columns encode piecewise-constant jumps at each index.
    Higher orders are generated by cumulative integration of this basis.
    """
    n = int(n)
    order = int(order)
    if n < 2:
        raise ValueError("n must be >= 2")
    if order < 0:
        raise ValueError("order must be >= 0")

    X = np.tril(np.ones((n, n - 1), dtype=float), k=-1)
    for _ in range(order):
        X = np.cumsum(X, axis=0)
    return X


def fit_trendfilter(
    y,
    *,
    n_effects: int = 10,
    order: int = 0,
    coef_threshold: float = 1e-6,
    susie_kwargs: dict | None = None,
) -> TrendFilterResult:
    """Fit a sparse trend-filter model using SuSiE on a jump basis."""
    from .susie import SuSiE

    y_arr = ensure_1d(y, name="y").astype(float, copy=False)
    X = trend_filter_design(y_arr.shape[0], order=order)

    kwargs = dict(susie_kwargs or {})
    kwargs.setdefault("standardize", False)
    kwargs.setdefault("intercept", True)

    model = SuSiE(n_effects=n_effects, **kwargs)
    model.fit(X, y_arr)
    signal = model.predict(X)

    coef = np.asarray(model.result_.coef, dtype=float)
    changepoints = np.where(np.abs(coef) > float(coef_threshold))[0] + 1

    return TrendFilterResult(
        design=X,
        signal=signal,
        changepoints=changepoints.astype(int),
        order=int(order),
        model=model,
        result=model.result_,
    )


__all__ = ["TrendFilterResult", "trend_filter_design", "fit_trendfilter"]
